### ISSUE TITLE
Problem in creating a view.

### ISSUE THREAD

**Issue by vincenzopalazzo** [leMaik/swing-material#10]
Hello,
I was trying to create a demo to understand how the library works but I can not render the components, What am I wrong?

here's what I tried and the rendering I get:

**_code_**
` public class MaterialDemo {

    public static void main(String[] args){
        MaterialFrame frame = new MaterialFrame();
        MaterialPanel panel = new MaterialPanel();
        panel.add(new MaterialButton());

        frame.setContentPane(panel);
        frame.setVisible(true);
        frame.setWindowSize(150,150);
        frame.setLocationRelativeTo(null);
    }
} `

**rendering**
![bug](https://user-images.githubusercontent.com/17150045/45265206-f15ece00-b447-11e8-9353-970374d98bb0.png)

**Comment by leMaik** [comment]
Sorry, didn't see this issue in time. Please take a look at our [one project that uses this library](https://github.com/TeamWertarbyte/craften-launcher) for some examples on how to use it.
