### ISSUE TITLE
How to use the TextToast or Toast Module?

### ISSUE THREAD

**Issue by eddyddoneyoh** [leMaik/swing-material#6]
I'm having difficulty using the TextToast.java or the Toast files. i really appreciate if you drop an example or implementation. thanks.

P.S. : thanks for this work. you rock :+1:

**Comment by leMaik** [comment]
Hi!

You need to add a `ToastBar` to your view, like [here](https://github.com/TeamWertarbyte/craften-launcher/blob/3040a5264f383f29f8904face14ab572317d8c0d/src/main/java/de/craften/craftenlauncher/gui/MainWindow.java#L56).

Then you can use that `ToastBar` to display a `Toast` like this (`toast` is an instance of a subclass of `Toast`, e.g. `TextToast`):

```java
toastBar.display(toast);
```

I hope this helps, we're working on adding some more examples. :+1:

**Comment by eddyddoneyoh** [comment]
Thank you leMaik... it worked perfectly. :-)

Thanks for the prompt reply!
